"""Wire types generated from ``openapi/v1.json`` — NEVER hand-edit.

Regenerate with ``python scripts/regenerate.py``; CI fails if this file and the
spec disagree. Import these through :mod:`bioflow_py.models`, which re-exports
them under their public names (``File`` is exposed as ``FileObject``).

Forward compatibility: server-sent string unions (statuses, event types, ...) are
OPEN sets — new values may appear without a major version, so these are typing
aids only. The SDK performs no runtime narrowing of responses.
"""

# generated by datamodel-codegen:
#   filename:  v1.json

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict

from bioflow_py._generated._compat import NotRequired


class CreatePageRequest(TypedDict):
    title: str
    theme_preset_key: NotRequired[str]
    header_layout: NotRequired[Literal["classic", "banner", "hero", "cutout"]]


class BlockUpdate(TypedDict):
    block_id: str
    data: dict[str, Any]


BlockOrderItem: TypeAlias = str


class UpdatePageRequest(TypedDict):
    expected_updated_at: str
    title: NotRequired[str]
    description: NotRequired[str]
    theme_preset_key: NotRequired[str]
    block_updates: NotRequired[list[BlockUpdate]]
    block_order: NotRequired[list[BlockOrderItem]]


class AddBlockRequest(TypedDict):
    expected_updated_at: str
    kind: str
    data: NotRequired[dict[str, Any]]
    file_url: NotRequired[str]
    file_name: NotRequired[str]


class PublishPageRequest(TypedDict):
    starts_at: NotRequired[str]


class CreateWebhookEndpointRequest(TypedDict):
    url: str
    event_types: list[Literal["contact.created", "page.published", "sale.paid", "sale.refunded"]]


class UpdateWebhookEndpointRequest(TypedDict):
    url: NotRequired[str]
    event_types: NotRequired[list[Literal["contact.created", "page.published", "sale.paid", "sale.refunded"]]]
    enabled: NotRequired[bool]


class ReplayWebhooksRequest(TypedDict):
    since: str


class Totals(TypedDict):
    views: int
    clicks: int
    unique_visitors: int
    ctr_percent: float


class TopLink(TypedDict):
    label: str
    url: str
    clicks: int
    page_title: str


class TopReferrer(TypedDict):
    label: str
    views: int


class Tips(TypedDict):
    count: int
    total_gross_cents: int
    refunded_count: int
    unique_fans: int
    currency: str | None


class AnalyticsSummary(TypedDict):
    range_days: int
    totals: Totals
    top_links: list[TopLink]
    top_referrers: list[TopReferrer]
    tips: Tips


class Error(TypedDict):
    pointer: str
    code: str
    message: str


class Problem(TypedDict):
    """
    RFC 9457 problem details
    """

    type: str
    title: str
    status: int
    detail: NotRequired[str]
    instance: str
    code: Literal["invalid_request", "invalid_api_key", "insufficient_scope", "feature_not_enabled", "test_key_read_only", "resource_not_found", "stale_snapshot", "idempotency_in_progress", "idempotency_key_reused", "endpoint_verification_failed", "endpoint_limit_reached", "rate_limited", "quota_exhausted", "internal_error"]
    request_id: str
    errors: NotRequired[list[Error]]


class Contact(TypedDict):
    id: str
    email: str
    name: str | None
    source: str
    source_block_id: str | None
    created_at: str


class File(TypedDict):
    id: str
    name: str
    mime_type: str
    public_path: str
    download_path: str
    size_bytes: int
    created_at: str


class PageSummary(TypedDict):
    id: str
    title: str
    slug: str
    status: Literal["DRAFT", "PUBLISHED", "ARCHIVED"]
    block_count: int
    public_url: str | None
    updated_at: str


class Theme(TypedDict):
    label: str
    preset_key: str


class Published(TypedDict):
    is_live: bool
    block_count: int
    live_updated_at: str | None


class PageBlockRef(TypedDict):
    id: str
    kind: str
    enabled: bool
    label: str


class Meter(TypedDict):
    name: str
    used: int
    limit: int
    remaining: int


class Burst(TypedDict):
    per_minute: int


class Usage(TypedDict):
    plan: str
    period_start: str
    period_end: str
    meters: list[Meter]
    burst: Burst


class WebhookEndpoint(TypedDict):
    """
    A webhook endpoint. The whsec_ signing secret is returned ONLY by Create and Rotate secret — never here.
    """

    id: str
    url: str
    status: Literal["ACTIVE", "DISABLED"]
    disabled_reason: str | None
    event_types: list[Literal["contact.created", "page.published", "sale.paid", "sale.refunded"]]
    consecutive_failures: int
    last_success_at: str | None
    last_failure_at: str | None
    previous_secret_expires_at: str | None
    created_at: str
    updated_at: str


class CreateWebhookEndpointResponse(TypedDict):
    endpoint: WebhookEndpoint
    secret: str


class WebhookAttempt(TypedDict):
    number: int
    status_code: int | None
    error: str | None
    duration_ms: int
    at: str


class WebhookReplayResult(TypedDict):
    replayed: int


class RotateWebhookSecretResponse(TypedDict):
    endpoint: WebhookEndpoint
    secret: str
    previous_secret_expires_at: str


class WebhookTestResult(TypedDict):
    delivered: bool
    status_code: int | None
    error: str | None


class ContactList(TypedDict):
    data: list[Contact]
    has_more: bool
    next_cursor: str | None


class FileList(TypedDict):
    data: list[File]
    has_more: bool
    next_cursor: str | None


class PageList(TypedDict):
    data: list[PageSummary]
    has_more: bool
    next_cursor: str | None


class Draft(TypedDict):
    updated_at: str
    block_count: int
    blocks: list[PageBlockRef]


class Page(TypedDict):
    id: str
    title: str
    description: str
    slug: str
    status: Literal["DRAFT", "PUBLISHED", "ARCHIVED"]
    locale: str
    public_url: str | None
    theme: Theme
    draft: Draft
    published: Published


class PublishResult(TypedDict):
    page: Page
    scheduled_for: str | None


class WebhookEndpointList(TypedDict):
    data: list[WebhookEndpoint]


class WebhookDelivery(TypedDict):
    id: str
    event_id: str
    event_type: str
    status: Literal["PENDING", "SUCCEEDED", "FAILED"]
    attempt_count: int
    next_attempt_at: str | None
    last_status_code: int | None
    created_at: str
    attempts: list[WebhookAttempt]


class WebhookDeliveryList(TypedDict):
    data: list[WebhookDelivery]
    has_more: bool
    next_cursor: str | None
